---

  - name: Borramos defaults inservibles
    package:
      state: absent
      name: "{{item}}"
    with_items:
      - vim.tiny # despues instalamos el full
      - vlc # no me gusta
      - gimp # no me gusta
      - onboard # no me gusta
      # - thunderbird
      - mono-runtime-common # security risk
      - gnome-orca # security risk
      - orca # security risk
      # - safeeyes # Brake reminder
    become: true

  - name: Instalaciones de applicaciones con package manager
    package:
      name: "{{item}}"
    with_items:
      - python3-pip
      - dconf-editor # Programa para editar comportamientos de linux
      - nfs-common # Necesario para compartir carpetas con nfs para montar con linux
      - gnome-color-manager # Color schemes for different monitors
      - tree # Tree
      - firefox #
      - vim # Editor
      - gawk
      - gitk # Recomendaria grv para la consola
      - mc # Midnight commander
      - direnv # Environment switcher for the shell
      - virtualbox # VM
      - mycli # MySql command line
      - inkscape # Drawings in SVG
      - skypeforlinux
      - samba # Dancing application?
      - numlockx # The most important app in the world
      - safeeyes # Brake reminder
      - redshift # Bluelight filter
    become: yes

  - name: Chequeamos si hay algun archivo de config de mycli
    stat:
      path: "{{mycli_config_file}}"
    register: mycli_conf

  - name: Configuramos Mycli
    template:
      dest: "{{mycli_config_file}}"
      src: mycli.conf
      force: yes
    when: not mycli_conf.stat.exists

  # extra configs
  - name: Configuramos aplicaciones
    block:
    - name: Configuramos redshift
      template:
        dest: "{{redshift_config_file}}"
        src: redshift.conf
        force: yes
