---
- name: Chequeamos si esta instalada la fuente jetbrainsmono
  stat:
    path: "{{jetbrainsmono_path}}"
  register: jetbrainsmono_installed

- name: jetbrainsmono
  block:

  - name: Creamos directorio para jetbrainsmono
    file:
      state: directory
      path: "{{jetbrainsmono_path}}"
      owner: "{{user}}"

  - name: Unzip
    unarchive:
      src: "JetBrainsMono-2.001.zip"
      dest: "{{jetbrainsmono_path}}"
      remote_src: no
      owner: "{{user}}"

  when: jetbrainsmono_installed.stat.exists == False
