---

  - name: Instalamos fuentes
    block:

    - name: Creamos directorio de fuentes
      file:
        state: directory
        path: "{{fonts_path}}"

    - name: MS-Core-Fonts
      block:
      - name: Truco para aceptar terminos y condiciones de mscorefonts
        debconf:
          name: ttf-mscorefonts-installer
          question: msttcorefonts/accepted-mscorefonts-eula
          value: "true"
          vtype: select

      - name: Truco para aceptar terminos y condiciones de mscorefonts
        debconf:
          name: ttf-mscorefonts-installer
          question: msttcorefonts/present-mscorefonts-eula
          value: ""
          vtype: select

      - name: Instalamos fuentes por apt-get
        package:
          name: "{{item}}"
        with_items:
          - ttf-mscorefonts-installer
          - fonts-hack
          - fonts-noto
          - fonts-firacode

    - name: Source-Code-Pro
      import_tasks: source_code.yml

    - name: Roboto
      import_tasks: roboto.yml

    - name: Nunito
      import_tasks: nunito.yml

    - name: Jetbrainsmono
      import_tasks: jetbrainsmono.yml

    - name: Actualizamos cache de fuentes
      command: "fc-cache -f -v"

    become: yes
